version: '3.8'

services:
  frontend:
    container_name: nuxt3-art-cms
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - '9090:9090'
    env_file: .env
